[package]
name = "chat"
version = "0.1.0"
edition = "2021"
authors = ["psiesta11"]

[dependencies]
ws = "0.9.1"
serde_json = "1.0.67"
serde = {version = "1.0.130", features = ["derive"]}
rusqlite = "0.25.3"
r2d2 = "0.8.9"
r2d2_sqlite = "0.18.0"

# [profile.release]
# debug = true